import { createApi, fetchBaseQuery, FetchBaseQueryError } from '@reduxjs/toolkit/query/react'
import { Protocol } from '@baseswapfi/router-sdk'
import { TradeType } from '@baseswapfi/sdk-core'
import { FeeAmount, Pool, Route as V3Route } from '@baseswapfi/v3-sdk2'
import { Pair, Route as V2Route } from '@baseswapfi/v2-sdk'
import { getClientSideQuote } from 'lib/hooks/routing/clientSideSmartOrderRouter'
import ms from 'ms'
